### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by CN91** [ArdaXi/Minilodon#1]
Minilodon kan crashen als chatters verkeerde encoding aan hebben staan voor special chars. De error waarmee hij crasht is als volgt: 

 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80   

Er staat geen regelnr. bij de error maar mijn vermoeden is dat het te maken heeft met de logging module.  Want hij crasht instant op het gebruik van de character.

**Comment by ArdaXi** [comment]
Should be fixed by 559bb65

Leaving this open for now.

**Comment by CN91** [comment]
Seems to be fixed  😃
